In [1]:
import pandas as pd
import pandera as pa

In [2]:
valores_ausentes = ['###!','####','**','****','*****','NULL']
df = pd.read_csv("ocorrencia_2010_2020.csv", parse_dates=['ocorrencia_dia'], dayfirst=True, na_values = valores_ausentes) ##alterando os não informados
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0.0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0.0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0.0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0.0
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0.0
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0.0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0

In [3]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo":pa.Column(pa.Int, required=False), ##caso a coluna seja opcional
        "codigo_ocorrencia": pa.Column(pa.Int),
        "codigo_ocorrencia2": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade": pa.Column(pa.String, nullable=True), ##Possui null
        "ocorrencia_uf": pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        "ocorrencia_aerodromo": pa.Column(pa.String, nullable=True),
        "ocorrencia_dia": pa.Column(pa.DateTime, nullable=True),
        "ocorrencia_hora": pa.Column(pa.String,pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        "total_recomendacoes": pa.Column(pa.Float, nullable=True)
    }
)

In [4]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0.0
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0.0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0.0
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0.0
...,...,...,...,...,...,...,...,...,...
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0.0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0.0
5751,79844,79844,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN

In [5]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
dtype: object

In [6]:
df.loc[1] ##label

codigo_ocorrencia                         40349
codigo_ocorrencia2                        40349
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                         BELÉM
ocorrencia_uf                                PA
ocorrencia_aerodromo                       SBBE
ocorrencia_dia              2010-01-03 00:00:00
ocorrencia_hora                        11:05:00
total_recomendacoes                         0.0
Name: 1, dtype: object

In [7]:
df.iloc[-1] ##indice

codigo_ocorrencia               79844
codigo_ocorrencia2              79844
ocorrencia_classificacao    INCIDENTE
ocorrencia_cidade                 NaN
ocorrencia_uf                     NaN
ocorrencia_aerodromo              NaN
ocorrencia_dia                    NaT
ocorrencia_hora                   NaN
total_recomendacoes               NaN
Name: 5751, dtype: object

In [8]:
df.tail()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5749,79802,79802,INCIDENTE,RIO DE JANEIRO,RJ,SBGL,2020-12-30,00:54:00,0.0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0.0
5751,79844,79844,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN

In [9]:
df.iloc[10:15] ##fatiar por índice

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,39789,39789,INCIDENTE,SÃO PEDRO DO SUL,RS,NaN,2010-01-10,21:30:00,0.0
11,40069,40069,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0
12,40414,40414,INCIDENTE,BRASÍLIA,DF,SBBR,2010-01-10,03:00:00,0.0
13,39507,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2.0
14,40107,40107,ACIDENTE,GURUPÁ,PA,SNGU,2010-01-12,14:30:00,0.0

In [10]:
df.loc[10:15] ##inclui o final

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,39789,39789,INCIDENTE,SÃO PEDRO DO SUL,RS,NaN,2010-01-10,21:30:00,0.0
11,40069,40069,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0
12,40414,40414,INCIDENTE,BRASÍLIA,DF,SBBR,2010-01-10,03:00:00,0.0
13,39507,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2.0
14,40107,40107,ACIDENTE,GURUPÁ,PA,SNGU,2010-01-12,14:30:00,0.0
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0

In [11]:
df.loc[:,'ocorrencia_uf']

0        RJ
1        PA
2        RJ
3        MT
4        RS
       ...
5747     SP
5748     TO
5749     RJ
5750     MS
5751    NaN
Name: ocorrencia_uf, Length: 5752, dtype: object

In [12]:
df['ocorrencia_uf']

0        RJ
1        PA
2        RJ
3        MT
4        RS
       ...
5747     SP
5748     TO
5749     RJ
5750     MS
5751    NaN
Name: ocorrencia_uf, Length: 5752, dtype: object

In [13]:
df.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade             12
ocorrencia_uf                 13
ocorrencia_aerodromo        2355
ocorrencia_dia                12
ocorrencia_hora               13
total_recomendacoes           12
dtype: int64

In [14]:
df.loc[df.ocorrencia_uf.isnull()] ##busca isnull

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2227,49474,49474,ACIDENTE,ÁGUAS INTERNACIONAIS,NaN,NaN,2013-09-02,02:54:00,0.0
2920,52697,52697,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
2987,52948,52948,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
4459,79567,79567,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
4491,78035,78035,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
4700,78324,78324,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5472,79385,79385,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
5514,79445,79445,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5544,79481,79481,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5624,79582,79582,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5664,79663,79663,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
5735,79799,79799,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5751,79844,79844,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN

In [15]:
filtro_nauf =df.ocorrencia_uf.isnull()
df.loc[filtro_nauf]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2227,49474,49474,ACIDENTE,ÁGUAS INTERNACIONAIS,NaN,NaN,2013-09-02,02:54:00,0.0
2920,52697,52697,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
2987,52948,52948,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
4459,79567,79567,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
4491,78035,78035,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
4700,78324,78324,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5472,79385,79385,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
5514,79445,79445,ACIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5544,79481,79481,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5624,79582,79582,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5664,79663,79663,INCIDENTE GRAVE,NaN,NaN,NaN,NaT,NaN,NaN
5735,79799,79799,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN
5751,79844,79844,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN

In [16]:
filtro_naaero =df.ocorrencia_aerodromo.isnull()
df.loc[filtro_naaero]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0.0
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0.0
5,39807,39807,INCIDENTE,SALVADOR,BA,NaN,2010-01-06,17:53:00,0.0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0
...,...,...,...,...,...,...,...,...,...
5744,79753,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0.0
5745,79755,79755,ACIDENTE,MATO RICO,PR,NaN,2020-12-29,10:30:00,0.0
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0.0
5751,79844,79844,INCIDENTE,NaN,NaN,NaN,NaT,NaN,NaN

In [17]:
df.count() ##não conta 'na'

codigo_ocorrencia           5752
codigo_ocorrencia2          5752
ocorrencia_classificacao    5752
ocorrencia_cidade           5740
ocorrencia_uf               5739
ocorrencia_aerodromo        3397
ocorrencia_dia              5740
ocorrencia_hora             5739
total_recomendacoes         5740
dtype: int64

In [18]:
#ocorrencias com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
63,39992,39992,ACIDENTE,SÃO PAULO,SP,SBMT,2010-02-17,20:07:00,11.0
326,42250,42250,ACIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-08-12,12:26:00,19.0
530,43471,43471,ACIDENTE,SÃO PAULO,SP,NaN,2010-12-14,20:15:00,11.0
727,44377,44377,ACIDENTE,ITÁPOLIS,SP,SDIO,2011-04-09,14:50:00,11.0
872,44796,44796,ACIDENTE,RECIFE,PE,SBRF,2011-07-13,09:54:00,23.0
884,44888,44888,INCIDENTE GRAVE,SÃO JOSÉ DOS PINHAIS,PR,SBCT,2011-07-15,17:05:00,11.0
1062,45554,45554,INCIDENTE GRAVE,UBERLÂNDIA,MG,SBUL,2011-11-15,02:15:00,20.0
1972,47938,47938,INCIDENTE,BRASÍLIA,DF,SBBR,2013-04-13,18:00:00,11.0
2795,52265,52265,ACIDENTE,SANTOS,SP,NaN,2014-08-13,13:03:00,13.0
3930,66432,66432,INCIDENTE GRAVE,VITÓRIA,ES,NaN,2017-02-21,11:47:00,12.0

In [19]:
#cidades com ocorrencias com mais de 10 recomendações 
filtro = df.total_recomendacoes > 10
df.loc[filtro, 'ocorrencia_cidade']

63                 SÃO PAULO
326           RIO DE JANEIRO
530                SÃO PAULO
727                 ITÁPOLIS
872                   RECIFE
884     SÃO JOSÉ DOS PINHAIS
1062              UBERLÂNDIA
1972                BRASÍLIA
2795                  SANTOS
3930                 VITÓRIA
Name: ocorrencia_cidade, dtype: object

In [20]:
#cidades com ocorrencias com mais de 10 recomendações e o total de recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro, ['ocorrencia_cidade','total_recomendacoes']]

         ocorrencia_cidade  total_recomendacoes
63               SÃO PAULO                 11.0
326         RIO DE JANEIRO                 19.0
530              SÃO PAULO                 11.0
727               ITÁPOLIS                 11.0
872                 RECIFE                 23.0
884   SÃO JOSÉ DOS PINHAIS                 11.0
1062            UBERLÂNDIA                 20.0
1972              BRASÍLIA                 11.0
2795                SANTOS                 13.0
3930               VITÓRIA                 12.0

In [21]:
#ocorrencias com classificação == "INCIDENTE GRAVE"
filtro = df.ocorrencia_classificacao == "INCIDENTE GRAVE"
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0
29,39709,39709,INCIDENTE GRAVE,CURITIBA,PR,SBBI,2010-01-23,16:36:00,2.0
35,39487,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0.0
...,...,...,...,...,...,...,...,...,...
5741,79754,79754,INCIDENTE GRAVE,NOVA MARINGÁ,MT,NaN,2020-12-28,13:00:00,0.0
5744,79753,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0.0
5746,79769,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0.0
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0.0

In [22]:
#cidades com ocorrencias com classificação == "INCIDENTE GRAVE" no estado "SP"
filtro1 = df.ocorrencia_classificacao == "INCIDENTE GRAVE"
filtro2 = df.ocorrencia_uf == "SP"
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
136,40270,40270,INCIDENTE GRAVE,PIRASSUNUNGA,SP,SDPY,2010-04-15,20:15:00,0.0
171,40620,40620,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2010-05-06,15:50:00,0.0
219,41411,41411,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2010-06-08,19:30:00,2.0
297,42289,42289,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2010-07-29,20:06:00,0.0
314,42323,42323,INCIDENTE GRAVE,SÃO JOSÉ DO RIO PRETO,SP,SBSR,2010-08-05,12:01:00,0.0
...,...,...,...,...,...,...,...,...,...
5591,79540,79540,INCIDENTE GRAVE,SÃO PAULO,SP,NaN,2020-09-12,13:10:00,0.0
5610,79566,79566,INCIDENTE GRAVE,REGENTE FEIJÓ,SP,SDYJ,2020-09-27,19:33:00,0.0
5704,79739,79739,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0.0
5705,79705,79705,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0.0
5715,79718,79718,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0.0

In [23]:
#cidades com ocorrencias com classificação == "INCIDENTE GRAVE" ou estado "SP"
filtro1 = df.ocorrencia_classificacao == "INCIDENTE GRAVE"
filtro2 = df.ocorrencia_uf == "SP"
df.loc[filtro1 | filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
9,39711,39711,INCIDENTE GRAVE,PARÁ DE MINAS,MG,NaN,2010-01-10,20:00:00,0.0
11,40069,40069,ACIDENTE,SÃO PAULO,SP,SBMT,2010-01-10,14:50:00,8.0
16,39809,39809,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0
...,...,...,...,...,...,...,...,...,...
5744,79753,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0.0
5746,79769,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0.0
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0
5748,79757,79757,INCIDENTE GRAVE,LAGOA DA CONFUSÃO,TO,NaN,2020-12-30,18:30:00,0.0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0.0

In [24]:
#cidades com ocorrencias com classificação == "INCIDENTE GRAVE" ou classificação == "INCIDENTE" no estado "SP"
filtro1 = (df.ocorrencia_classificacao == "INCIDENTE GRAVE") | (df.ocorrencia_classificacao == "INCIDENTE") #() para mostrar a sequencia da análise
filtro2 = df.ocorrencia_uf == "SP"
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
16,39809,39809,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0
18,39828,39828,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0.0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0.0
27,39768,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0.0
33,39848,39848,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0.0
...,...,...,...,...,...,...,...,...,...
5704,79739,79739,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0.0
5705,79705,79705,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0.0
5715,79718,79718,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0.0
5742,79800,79800,INCIDENTE,SÃO PAULO,SP,SBMT,2020-12-28,10:15:00,0.0
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0

In [25]:
#cidades com ocorrencias com classificação == "INCIDENTE GRAVE" ou classificação == "INCIDENTE" no estado "SP"
filtro1 = df.ocorrencia_classificacao.isin (['INCIDENTE GRAVE','INCIDENTE']) #isin busca na lista ao inves de colocar vários "or"
filtro2 = df.ocorrencia_uf == "SP"
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
16,39809,39809,INCIDENTE,SÃO PAULO,SP,NaN,2010-01-15,15:00:00,0.0
18,39828,39828,INCIDENTE,SANTOS,SP,NaN,2010-01-15,17:45:00,0.0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0.0
27,39768,39768,INCIDENTE,CAMPINAS,SP,NaN,2010-01-21,20:45:00,0.0
33,39848,39848,INCIDENTE,GUARULHOS,SP,SBGR,2010-01-25,17:05:00,0.0
...,...,...,...,...,...,...,...,...,...
5704,79739,79739,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2020-12-03,14:42:00,0.0
5705,79705,79705,INCIDENTE GRAVE,SOROCABA,SP,SDCO,2020-12-04,15:30:00,0.0
5715,79718,79718,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2020-12-11,13:50:00,0.0
5742,79800,79800,INCIDENTE,SÃO PAULO,SP,SBMT,2020-12-28,10:15:00,0.0
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0

In [26]:
#ocorrencias cuja a cidade comece com "c"
filtro = df.ocorrencia_cidade.str[0] == 'C'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,40215,40215,INCIDENTE,COARI,AM,SBUY,2010-01-07,18:40:00,0.0
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
8,39156,39156,INCIDENTE GRAVE,CASCAVEL,PR,SBCA,2010-01-10,23:15:00,2.0
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0
20,40310,40310,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2010-01-18,19:32:00,0.0
...,...,...,...,...,...,...,...,...,...
5661,79649,79649,INCIDENTE,CAMPINAS,SP,SBKP,2020-11-04,22:39:00,0.0
5663,79652,79652,INCIDENTE,CONFINS,MG,SBCF,2020-11-06,14:20:00,0.0
5680,79683,79683,INCIDENTE,CRUZEIRO DO SUL,AC,SBCZ,2020-11-16,22:00:00,0.0
5696,79692,79692,ACIDENTE,CATANDUVA,SP,SDCD,2020-11-28,12:50:00,0.0
5747,79804,79804,INCIDENTE,CAMPINAS,SP,SBKP,2020-12-29,19:00:00,0.0

In [27]:
#ocorrencias cuja a cidade terminam com "a"
filtro = df.ocorrencia_cidade.str[-1] == 'A'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
12,40414,40414,INCIDENTE,BRASÍLIA,DF,SBBR,2010-01-10,03:00:00,0.0
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0
25,39772,39772,INCIDENTE,UBERLÂNDIA,MG,NaN,2010-01-20,18:58:00,0.0
26,39847,39847,INCIDENTE,SOROCABA,SP,NaN,2010-01-20,13:10:00,0.0
...,...,...,...,...,...,...,...,...,...
5738,79787,79787,INCIDENTE,FORTALEZA,CE,SBFZ,2020-12-23,18:30:00,0.0
5739,79749,79749,ACIDENTE,MARITUBA,PA,NaN,2020-12-26,12:05:00,0.0
5743,79824,79824,ACIDENTE,RIO PARANAÍBA,MG,SNRP,2020-12-28,17:00:00,0.0
5744,79753,79753,INCIDENTE GRAVE,GOIATUBA,GO,NaN,2020-12-29,12:00:00,0.0
5750,79756,79756,INCIDENTE GRAVE,VICENTINA,MS,NaN,2020-12-31,09:00:00,0.0

In [28]:
#ocorrencias cuja a cidade terminam com "ma"
filtro = df.ocorrencia_cidade.str[-2:] == 'MA'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0
408,43062,43062,ACIDENTE,NOVO GAMA,GO,NaN,2010-09-25,16:30:00,1.0
688,44198,44198,ACIDENTE,BURITAMA,SP,NaN,2011-03-19,11:18:00,0.0
1035,51785,51785,INCIDENTE,BURITAMA,SP,SIBX,2011-10-25,19:15:00,0.0
1377,45939,45939,ACIDENTE,UMUARAMA,PR,NaN,2012-05-30,19:00:00,0.0
1401,46180,46180,ACIDENTE,AURIFLAMA,SP,NaN,2012-06-16,19:30:00,0.0
2099,49113,49113,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2013-06-15,12:00:00,4.0
2102,48799,48799,ACIDENTE,CANUTAMA,AM,NaN,2013-06-18,21:30:00,0.0
2655,51347,51347,INCIDENTE,DIADEMA,SP,NaN,2014-05-04,16:00:00,0.0
2855,52340,52340,ACIDENTE,FAMA,MG,NaN,2014-09-20,15:00:00,1.0
2966,52832,52832,ACIDENTE,BURITAMA,SP,NaN,2014-12-14,23:40:00,0.0
2997,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0.0
3040,52984,52984,ACIDENTE,NOVA LIMA,MG,SJLY,2015-02-01,15:10:00,0.0
3092,53596,53596,INCIDENTE,ITAPEMA,SC,NaN,2015-03-10,21:35:00,0.0
3157,53223,53223,ACIDENTE,PINDORAMA,SP,NaN,2015-04-22,12:45:00,0.0
3171,53265,53265,ACIDENTE,PACARAIMA,RR,SDMM,2015-05-05,16:05:00,2.0
3189,53271,53271,INCIDENTE GRAVE,UMUARAMA,PR,NaN,2015-05-17,17:00:00,0.0
3682,65414,65414,INCIDENTE GRAVE,NOVA LIMA,MG,SJLY,2016-07-08,19:50:00,1.0
3725,65633,65633,INCIDENTE GRAVE,NOVA LIMA,MG,NaN,2016-08-31,17:40:00,0.0
3881,66265,66265,ACIDENTE,BURITAMA,SP,NaN,2017-01-13,16:00:00,0.0
4229,77371,77371,ACIDENTE,CANUTAMA,AM,SDKH,2017-11-02,19:30:00,1.0
4311,77612,77612,ACIDENTE,ITAPEMA,SC,NaN,2018-01-06,10:30:00,0.0
4574,78080,78080,ACIDENTE,ITAPEMA,SC,NaN,2018-07-28,14:20:00,0.0
4986,78867,78867,INCIDENTE,IRACEMA,RR,NaN,2019-07-06,00:00:00,0.0
5070,78923,78923,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2019-09-03,14:00:00,0.0
5080,78782,78782,ACIDENTE,IVINHEMA,MS,NaN,2019-09-08,17:45:00,0.0
5405,79282,79282,ACIDENTE,ITURAMA,MG,NaN,2020-04-11,12:20:00,0.0
5440,79338,79338,INCIDENTE,IVINHEMA,MS,NaN,2020-05-15,09:40:00,0.0
5474,79400,79400,INCIDENTE,IBIRAMA,SC,NaN,2020-06-09,14:00:00,0.0

In [29]:
df['ocorrencia_cidade_bkp'] = df.ocorrencia_cidade

In [30]:
df.fillna(value={'ocorrencia_cidade':'Não info'}, inplace=True)

In [31]:
#ocorrencias cuja a cidade que contenham "ma"
filtro = df.ocorrencia_cidade.str.contains('MA')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp
7,39707,39707,INCIDENTE GRAVE,CANUTAMA,AM,NaN,2010-01-09,12:30:00,3.0,CANUTAMA
13,39507,39507,ACIDENTE,PRIMAVERA DO LESTE,MT,NaN,2010-01-11,17:00:00,2.0,PRIMAVERA DO LESTE
15,39315,39315,ACIDENTE,CANUTAMA,AM,NaN,2010-01-15,21:22:00,0.0,CANUTAMA
35,39487,39487,INCIDENTE GRAVE,PALMAS,TO,SBPJ,2010-01-26,16:50:00,0.0,PALMAS
78,39916,39916,INCIDENTE GRAVE,MANAUS,AM,SBEG,2010-03-07,19:35:00,2.0,MANAUS
...,...,...,...,...,...,...,...,...,...,...
5732,79745,79745,INCIDENTE,MARABÁ,PA,SBMA,2020-12-21,08:47:00,0.0,MARABÁ
5739,79749,79749,ACIDENTE,MARITUBA,PA,NaN,2020-12-26,12:05:00,0.0,MARITUBA
5741,79754,79754,INCIDENTE GRAVE,NOVA MARINGÁ,MT,NaN,2020-12-28,13:00:00,0.0,NOVA MARINGÁ
5745,79755,79755,ACIDENTE,MATO RICO,PR,NaN,2020-12-29,10:30:00,0.0,MATO RICO
5746,79769,79769,INCIDENTE GRAVE,MANOEL URBANO,AC,SIMB,2020-12-29,18:30:00,0.0,MANOEL URBANO

In [32]:
#ocorrencias cuja a cidade que contenham "ma" ou "al"
filtro = df.ocorrencia_cidade.str.contains('MA | AL')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp
110,40089,40089,ACIDENTE,VILA BELA DA SANTÍSSIMA TRINDADE,MT,NaN,2010-03-28,15:10:00,0.0,VILA BELA DA SANTÍSSIMA TRINDADE
130,40258,40258,INCIDENTE,MONTE ALEGRE,PA,NaN,2010-04-12,18:10:00,0.0,MONTE ALEGRE
131,40327,40327,INCIDENTE,PORTO ALEGRE,RS,NaN,2010-04-12,13:13:00,0.0,PORTO ALEGRE
133,40248,40248,INCIDENTE,PORTO ALEGRE,RS,SBPA,2010-04-13,18:47:00,0.0,PORTO ALEGRE
156,40572,40572,ACIDENTE,PORTO ALEGRE,RS,SBPA,2010-04-28,14:10:00,0.0,PORTO ALEGRE
...,...,...,...,...,...,...,...,...,...,...
5652,79645,79645,ACIDENTE,ALTO ALEGRE,RR,NaN,2020-10-28,12:25:00,0.0,ALTO ALEGRE
5659,79647,79647,INCIDENTE,PORTO ALEGRE,RS,SBPA,2020-11-01,18:20:00,0.0,PORTO ALEGRE
5679,79678,79678,ACIDENTE,VILA BELA DA SANTÍSSIMA TRINDADE,MT,NaN,2020-11-16,14:15:00,0.0,VILA BELA DA SANTÍSSIMA TRINDADE
5682,79684,79684,INCIDENTE,PORTO ALEGRE,RS,SBPA,2020-11-17,20:18:00,0.0,PORTO ALEGRE
5733,79759,79759,INCIDENTE,PORTO ALEGRE,RS,SBPA,2020-12-21,23:14:00,0.0,PORTO ALEGRE

In [34]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                float64
ocorrencia_cidade_bkp               object
dtype: object

In [35]:
#ocorrencias de 2015
filtro = df.ocorrencia_dia.dt.year == 2015
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp
2996,52992,52992,INCIDENTE GRAVE,SALVADOR,BA,SBSV,2015-01-01,11:40:00,3.0,SALVADOR
2997,52979,52979,ACIDENTE,IVINHEMA,MS,NaN,2015-01-02,14:50:00,0.0,IVINHEMA
2998,53073,53073,INCIDENTE,TEFÉ,AM,SBTF,2015-01-02,16:28:00,0.0,TEFÉ
2999,53074,53074,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-01-02,20:34:00,0.0,BELO HORIZONTE
3000,52976,52976,ACIDENTE,TOLEDO,PR,SBTD,2015-01-04,22:04:00,6.0,TOLEDO
...,...,...,...,...,...,...,...,...,...,...
3462,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0.0,ITABERÁ
3463,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0.0,GUARULHOS
3464,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0.0,SÃO FRANCISCO DO SUL
3465,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2.0,MAÇAMBARÁ
3466,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0.0,PORTO BELO

In [36]:
#ocorrencias de 2015 e mês 12
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 12
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp
3428,53573,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0.0,GUARULHOS
3429,60601,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0.0,PALMAS
3430,53634,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0.0,PALMAS
3431,53636,53636,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-02,17:42:00,0.0,JUNDIAÍ
3432,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0.0,CAMPOS DOS GOYTACAZES
3433,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0,BELO HORIZONTE
3434,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0,TRINDADE
3435,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0,AMERICANA
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0,AGUAÍ
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0,JALES
3438,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0,CAMPINAS
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0,CAXIAS DO SUL
3440,53627,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0.0,TERESINA
3441,60604,60604,INCIDENTE,GOIÂNIA,GO,SBGO,2015-12-12,14:34:00,0.0,GOIÂNIA
3442,60611,60611,INCIDENTE,SÃO PAULO,SP,SBSP,2015-12-12,15:30:00,0.0,SÃO PAULO
3443,60613,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0.0,JUSCIMEIRA
3444,60629,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0.0,RIO GRANDE
3445,53630,53630,INCIDENTE,MARÍLIA,SP,SBML,2015-12-13,13:50:00,0.0,MARÍLIA
3446,60603,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0.0,LONDRINA
3447,60612,60612,ACIDENTE,BENTO GONÇALVES,RS,SSBG,2015-12-13,20:30:00,0.0,BENTO GONÇALVES
3448,60783,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3.0,LAGES
3449,53639,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0.0,LOUVEIRA
3450,60609,60609,INCIDENTE GRAVE,ARAGUAÍNA,TO,SWGN,2015-12-15,13:00:00,0.0,ARAGUAÍNA
3451,60616,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0.0,PALOTINA
3452,60620,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4.0,RIO DE JANEIRO
3453,60645,60645,ACIDENTE,SERTÃOZINHO,SP,NaN,2015-12-15,13:00:00,0.0,SERTÃOZINHO
3454,60608,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0.0,BELO HORIZONTE
3455,60625,60625,ACIDENTE,ITÁPOLIS,SP,SDIO,2015-12-17,21:30:00,1.0,ITÁPOLIS
3456,60605,60605,INCIDENTE,UBERLÂNDIA,MG,SBUL,2015-12-18,10:25:00,0.0,UBERLÂNDIA
3457,60610,60610,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-18,18:45:00,0.0,JUNDIAÍ
3458,60602,60602,INCIDENTE,RIBEIRÃO PRETO,SP,SBRP,2015-12-22,06:27:00,0.0,RIBEIRÃO PRETO
3459,60615,60615,INCIDENTE,SÃO PAULO,SP,SBMT,2015-12-22,13:07:00,0.0,SÃO PAULO
3460,60640,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0.0,CASCAVEL
3461,60641,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0.0,BELO HORIZONTE
3462,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0.0,ITABERÁ
3463,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0.0,GUARULHOS
3464,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0.0,SÃO FRANCISCO DO SUL
3465,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2.0,MAÇAMBARÁ
3466,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0.0,PORTO BELO

In [37]:
#ocorrencias de 2015 e mês 12
filtro = (df.ocorrencia_dia.dt.year == 2015) & (df.ocorrencia_dia.dt.month == 12)
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp
3428,53573,53573,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-01,02:48:00,0.0,GUARULHOS
3429,60601,60601,INCIDENTE,PALMAS,TO,SBPJ,2015-12-01,16:05:00,0.0,PALMAS
3430,53634,53634,INCIDENTE,PALMAS,TO,SBPJ,2015-12-02,17:45:00,0.0,PALMAS
3431,53636,53636,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-02,17:42:00,0.0,JUNDIAÍ
3432,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0.0,CAMPOS DOS GOYTACAZES
3433,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0,BELO HORIZONTE
3434,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0,TRINDADE
3435,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0,AMERICANA
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0,AGUAÍ
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0,JALES
3438,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0,CAMPINAS
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0,CAXIAS DO SUL
3440,53627,53627,INCIDENTE,TERESINA,PI,SBTE,2015-12-12,19:05:00,0.0,TERESINA
3441,60604,60604,INCIDENTE,GOIÂNIA,GO,SBGO,2015-12-12,14:34:00,0.0,GOIÂNIA
3442,60611,60611,INCIDENTE,SÃO PAULO,SP,SBSP,2015-12-12,15:30:00,0.0,SÃO PAULO
3443,60613,60613,ACIDENTE,JUSCIMEIRA,MT,SWMO,2015-12-12,08:31:00,0.0,JUSCIMEIRA
3444,60629,60629,ACIDENTE,RIO GRANDE,RS,NaN,2015-12-12,10:40:00,0.0,RIO GRANDE
3445,53630,53630,INCIDENTE,MARÍLIA,SP,SBML,2015-12-13,13:50:00,0.0,MARÍLIA
3446,60603,60603,INCIDENTE,LONDRINA,PR,SBLO,2015-12-13,17:46:00,0.0,LONDRINA
3447,60612,60612,ACIDENTE,BENTO GONÇALVES,RS,SSBG,2015-12-13,20:30:00,0.0,BENTO GONÇALVES
3448,60783,60783,ACIDENTE,LAGES,SC,NaN,2015-12-13,14:00:00,3.0,LAGES
3449,53639,53639,INCIDENTE,LOUVEIRA,SP,SDAM,2015-12-15,14:20:00,0.0,LOUVEIRA
3450,60609,60609,INCIDENTE GRAVE,ARAGUAÍNA,TO,SWGN,2015-12-15,13:00:00,0.0,ARAGUAÍNA
3451,60616,60616,ACIDENTE,PALOTINA,PR,NaN,2015-12-15,20:30:00,0.0,PALOTINA
3452,60620,60620,ACIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-12-15,16:50:00,4.0,RIO DE JANEIRO
3453,60645,60645,ACIDENTE,SERTÃOZINHO,SP,NaN,2015-12-15,13:00:00,0.0,SERTÃOZINHO
3454,60608,60608,INCIDENTE,BELO HORIZONTE,MG,SBPR,2015-12-16,10:38:00,0.0,BELO HORIZONTE
3455,60625,60625,ACIDENTE,ITÁPOLIS,SP,SDIO,2015-12-17,21:30:00,1.0,ITÁPOLIS
3456,60605,60605,INCIDENTE,UBERLÂNDIA,MG,SBUL,2015-12-18,10:25:00,0.0,UBERLÂNDIA
3457,60610,60610,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-12-18,18:45:00,0.0,JUNDIAÍ
3458,60602,60602,INCIDENTE,RIBEIRÃO PRETO,SP,SBRP,2015-12-22,06:27:00,0.0,RIBEIRÃO PRETO
3459,60615,60615,INCIDENTE,SÃO PAULO,SP,SBMT,2015-12-22,13:07:00,0.0,SÃO PAULO
3460,60640,60640,INCIDENTE,CASCAVEL,PR,SBCA,2015-12-23,13:20:00,0.0,CASCAVEL
3461,60641,60641,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-23,15:53:00,0.0,BELO HORIZONTE
3462,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,NaN,2015-12-24,14:00:00,0.0,ITABERÁ
3463,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0.0,GUARULHOS
3464,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0.0,SÃO FRANCISCO DO SUL
3465,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,NaN,2015-12-28,19:00:00,2.0,MAÇAMBARÁ
3466,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0.0,PORTO BELO

In [38]:
#ocorrencias de 2015 e mês 12 e dia 8
filtro_ano = df.ocorrencia_dia.dt.year == 2015
filtro_mes = df.ocorrencia_dia.dt.month == 12
filtro_dia = df.ocorrencia_dia.dt.day == 8
df.loc[filtro_ano & filtro_mes & filtro_dia]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0,AGUAÍ
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0,JALES
3438,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0,CAMPINAS
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0,CAXIAS DO SUL

In [40]:
#ocorrencias de 2015 e mês 12 e do dia 3 ao 8
filtro_ano = df.ocorrencia_dia.dt.year == 2015
filtro_mes = df.ocorrencia_dia.dt.month == 12
filtro_dia = (df.ocorrencia_dia.dt.day > 2) & (df.ocorrencia_dia.dt.day < 9)
df.loc[filtro_ano & filtro_mes & filtro_dia]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp
3432,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0.0,CAMPOS DOS GOYTACAZES
3433,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0,BELO HORIZONTE
3434,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0,TRINDADE
3435,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0,AMERICANA
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0,AGUAÍ
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0,JALES
3438,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0,CAMPINAS
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0,CAXIAS DO SUL

In [41]:
#ocorrencias de 2015 e mês 12 e do dia 3 ao 8
filtro_ano = df.ocorrencia_dia.dt.year == 2015
filtro_mes = df.ocorrencia_dia.dt.month == 12
filtro_dia_inicio = df.ocorrencia_dia.dt.day > 2
filtro_dia_fim =df.ocorrencia_dia.dt.day < 9
df.loc[filtro_ano & filtro_mes & filtro_dia]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp
3432,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0.0,CAMPOS DOS GOYTACAZES
3433,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0.0,BELO HORIZONTE
3434,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3.0,TRINDADE
3435,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1.0,AMERICANA
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1.0,AGUAÍ
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0.0,JALES
3438,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0.0,CAMPINAS
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0.0,CAXIAS DO SUL

In [46]:
#criando coluna data e hora juntos
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' ' + df.ocorrencia_hora) #transformou ocorrencia_dia em string, concateou e transformou em data

In [52]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp,ocorrencia_dia_hora
0,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,NaN,2010-01-03,12:00:00,0,RIO DE JANEIRO,2010-01-03 12:00:00
1,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0,BELÉM,2010-01-03 11:05:00
2,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0,RIO DE JANEIRO,2010-01-03 03:00:00
3,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,NaN,2010-01-04,17:30:00,0,LUCAS DO RIO VERDE,2010-01-04 17:30:00
4,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0,PELOTAS,2010-01-05 19:25:00

In [49]:
df.fillna(value={'total_recomendacoes':'0'}, inplace=True)

In [50]:
df['total_recomendacoes'] = df.total_recomendacoes.astype(int)

In [51]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int32
ocorrencia_cidade_bkp               object
ocorrencia_dia_hora         datetime64[ns]
dtype: object

In [53]:
#ocorrencias de 2015 e mês 12 e do dia 3 ao 8
filtro_ano = df.ocorrencia_dia_hora.dt.year == 2015
filtro_mes = df.ocorrencia_dia_hora.dt.month == 12
filtro_dia_inicio = df.ocorrencia_dia_hora.dt.day > 2
filtro_dia_fim =df.ocorrencia_dia_hora.dt.day < 9
df.loc[filtro_ano & filtro_mes & filtro_dia]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp,ocorrencia_dia_hora
3432,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0,CAMPOS DOS GOYTACAZES,2015-12-03 10:50:00
3433,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,BELO HORIZONTE,2015-12-03 16:47:00
3434,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,TRINDADE,2015-12-06 13:10:00
3435,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,AMERICANA,2015-12-06 15:00:00
3436,53628,53628,ACIDENTE,AGUAÍ,SP,NaN,2015-12-08,14:30:00,1,AGUAÍ,2015-12-08 14:30:00
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0,JALES,2015-12-08 10:20:00
3438,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0,CAMPINAS,2015-12-08 16:19:00
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,CAXIAS DO SUL,2015-12-08 13:00:00

In [55]:
#ocorrencias de 2015 e mês 12 e do dia 3 ao 8 das 11 as 13 horas
filtro_hora_inicio = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro_hora_fim =  df.ocorrencia_dia_hora <= '2015-12-08 13:00:00'
df.loc[filtro_hora_inicio & filtro_hora_fim]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_cidade_bkp,ocorrencia_dia_hora
3433,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,BELO HORIZONTE,2015-12-03 16:47:00
3434,53625,53625,ACIDENTE,TRINDADE,GO,NaN,2015-12-06,13:10:00,3,TRINDADE,2015-12-06 13:10:00
3435,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,AMERICANA,2015-12-06 15:00:00
3437,53629,53629,ACIDENTE,JALES,SP,SDJL,2015-12-08,10:20:00,0,JALES,2015-12-08 10:20:00
3439,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,CAXIAS DO SUL,2015-12-08 13:00:00